/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hehongli' at '18-8-9 下午5:11' with Gradle 2.14.1
 *
 * @author hehongli, @date 18-8-9 下午5:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
